### ISSUE TITLE
Resolution of existing PRs and issues

### ISSUE THREAD

**Issue by bthompson90** [npm/policies#117]
I noticed that all of the open PRs and discussions (aside from one) are three years old.  Is this because it's very difficult to get a change into this repository or it's just not a priority for the npm community right now?  If it's a matter of time, I'd be interested in helping resolve some of these outstanding issues and PRs.

I'm being curious, not critical.

Thanks!

**Comment by kemitchell** [comment]
#48 is waiting for word from @seldo. #45 is on me.

@bthompson90, you should feel free to propose feedback or changes here, as others have. Some items that come up here are inherently long-lead. But every set of public terms can always be improved.

I don't think npm, Inc. will delegate maintainer duties, like merging or managing, in this repo.

**Comment by Tikhon88** [comment]
Ребята помогайте
