### ISSUE TITLE
[QUESTION] bot downloading packages are against npm tos or not?

### ISSUE THREAD

**Issue by sayantan300** [npm/policies#143]
As u all know, npm has bots which download a pkg whenever it has got an update... But my friend got to know this trick and he has made a bot which will ping the .tgz link of my package, so I will get more downloads, and he's saying he did that so my pkg will be removed by npm because of doing that... So will my pkg be removed because of that?

**Comment by MylesBorins** [comment]
Closing this issue as we are archiving this repository. The policies are now being managed in the [documentation repository](https://github.com/npm/documentation/tree/main/content/policies)
