### ISSUE TITLE
Expand dispute resolution policy to cover user name disputes

### ISSUE THREAD

**Issue by kemitchell** [npm/policies#19]
cc @isaacs @seldo

**Comment by kemitchell** [comment]
also cc @ehsalazar and @stephanie

**Comment by ashleygwilliams** [comment]
this is being handled in #48

**Comment by MylesBorins** [comment]
Closing this issue as we are archiving this repository. The policies are now being managed in the [documentation repository](https://github.com/npm/documentation/tree/main/content/policies)
