### ISSUE TITLE
Open Source Terms are too broad

### ISSUE THREAD

**Issue by rmg** [npm/policies#30]
The Open Source Terms contain a rather ambiguous clause:

> You own Your Content, but grant npm a license to use it free of charge.
> That license allows npm to do whatever it needs to do with your content,
> within reason, to provide and improve npm Services, for you and other
> users. That license lasts, for each piece of Your Content, until the
> last copy disappears from npm's backups, caches, and other systems,
> after you delete it from the Website or the Public Registry.

While I'm quite certain this is intended to allow npm Inc. to move files around and distribute them as needed, the actual phrasing is "**grant npm a license to use it free of charge**" which suggest npm can actually _use_ the software in the package.

I'm not a lawyer, but I am a paranoid pedant, and that's almost the same thing, right?

/cc @isaacs

**Comment by kemitchell** [comment]
Howdy!

Just for the benefit of others who aren't aware: I'm legal counsel for npm, Inc. They've instructed me to do as much as I can on the terms and policies here on GitHub, as transparently as possible. That does _not_ include giving legal advice. (Don't rely on what I say for your own purposes. Get your own lawyer and talk your needs through with them.) But it _does_ include responding to and incorporating good feedback from the community.

@rmg, this is great feedback. Something was lost rendering the more limited license we had in mind, which you might also guess was longer and less accessible, into plain English.

I can do better. You'll see a PR here soon.

**Comment by scriptjs** [comment]
I will not I would like these questions answered hat were asked in the other thread:

> After re-reading what you wrote about the phrase in the open source terms, I will add the passage in your terms seems to overstep what NPM's involvement is in distribution and providing service to users. This requires access and use of the metadata the distribution of a tarball. Can you explain how this should be more than this? What else is reasonable use of our software in the context of the service you provide?
```
You own Your Content, but grant npm a license to use it free of charge. 
That license allows npm to do whatever it needs to do with your content, 
within reason, to provide and improve npm Services, for you and other users. 
```

**Comment by rmg** [comment]
Thanks, @kemitchell. I'm looking forward to helping review the PR if/when you want feedback on it :-)

**Comment by kemitchell** [comment]
@rmg, really appreciate you feeding this back to us here!

**Comment by mk-pmb** [comment]
> What else is reasonable use of our software in the context of the service you provide?

I'd like if npm had permission to re-format, transpile and re-compile packages. There will be a day when we get a new cool technology, and some authors of really neat packages by then won't have the time or motivation to upgrade soon.
