### ISSUE TITLE
Email address legal@npmjs.com doesn't exist

### ISSUE THREAD

**Issue by rmg** [npm/policies#31]
Before filing #30 I tried sending an email to legal@npmjs.com as indicated in open-source-terms.md but it bounced. I send then send it to support@npmjs.com, which worked.

I'm assuming the other npmjs.com addresses in this repo all work, but if it saves someone grepping them, they are abuse@npmjs.com, isaacs@npmjs.com, jobs@npmjs.com, and privacy@npmjs.com.

**Comment by isaacs** [comment]
Should be working now.
