### ISSUE TITLE
Reconcile Code of Conduct's "Acceptable Package Content" with Terms' "Acceptable Use"

### ISSUE THREAD

**Issue by kemitchell** [npm/policies#35]
As mentioned in an anticipatory comment in the Code of Conduct, guidelines on what does and does not belong in packages on the public registry should end up in the (new) Open Source terms of use. A few of the guidelines are already mirrored in the terms, but there's a little reconciliation to do, too.

This one's for me.

**Comment by ashleygwilliams** [comment]
bump, @kemitchell

**Comment by kemitchell** [comment]
ACK

**Comment by LooTKinGz** [comment]
Update filed

**Comment by MylesBorins** [comment]
Closing this issue as we are archiving this repository. The policies are now being managed in the [documentation repository](https://github.com/npm/documentation/tree/main/content/policies)
