### ISSUE TITLE
Document list of reserved names

### ISSUE THREAD

**Issue by kevinSuttle** [npm/policies#36]
See also: kevinSuttle/github#3

Should probably be linked to, or published here: https://www.npmjs.com/policies/disputes

**Comment by ashleygwilliams** [comment]
hi @kevinSuttle ! can you please be more explicit about the exact thing you'd like to see implemented here? i am guessing you'd like the list of usernames documented- if so where?

**Comment by ashleygwilliams** [comment]
ok! thanks for the clarification @kevinSuttle - i'm on it!

**Comment by ashleygwilliams** [comment]
for future reference- this might be more appropriately filed on npm/registry (which did not exist when you first filed, so of course, no worries on that)

**Comment by kemitchell** [comment]
Looks like this has been reopened on npm/registry. Closing here.
