### ISSUE TITLE
Out of date duplicate dispute policy page

### ISSUE THREAD

**Issue by wheresrhys** [npm/policies#40]
https://docs.npmjs.com/misc/disputes does not match the content of https://github.com/npm/policies/blob/master/disputes.md, unlike https://www.npmjs.com/policies/disputes (which I assume is the current up to date reference)

Without knowing where the content for https://docs.npmjs.com/misc/disputes is hosted I can't really suggest where or how to fix it, but there's potential for confusion if this and other npm policies don't have a single source of truth.

The out of date page is higher than the correct one in google https://www.google.co.uk/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=npm%20dispute

**Comment by ashleygwilliams** [comment]
could you file this as a bug on the npm docs repo? https://github.com/npm/docs/issues thanks for this!

**Comment by wheresrhys** [comment]
Sure, will do.

As an additional resolution, GitHub seem very open these days to refining
their issues workflow Would you mind raising a request with GitHub to allow
reassigning issues to a more appropriate repo. I'll do so myself too, but
I'm sure a request from npm would carry more weight.

Asking issue raisers to duplicate their effort to open another issue on
another repo is definitely sub optimal workflow. If you had a UI available
to move an issue to where it should've been raised that'd be better for
everyone :)

**Comment by ashleygwilliams** [comment]
oh that is a super neat idea. i met brandon keepers, the keeper of GitHub open source and have been meaning to have a chitchat with him anyways :) thanks for the idea!

**Comment by mikermcneil** [comment]
@wheresrhys @ashleygwilliams we usually use https://github-issue-mover.appspot.com/ -- comes in handy in the ole bookmark bar
