### ISSUE TITLE
registration form says email is not shared, but it is shared

### ISSUE THREAD

**Issue by jdxcode** [npm/policies#98]
The registration form has this line:
<img width="723" alt="screen shot 2018-08-30 at 9 48 41 am" src="https://user-images.githubusercontent.com/216188/44866448-2134f700-ac3a-11e8-9382-5d19bc882a8e.png">

But if anyone visits my profile page then the email is shared. People can also get my email with the CLI so it is shared.

**Comment by bthompson90** [comment]
A little contradictory I suppose.  I think the intent is that npm will never share it or sell it outside of the npm community, or use it for commercial purposes/profits.

**Comment by kemitchell** [comment]
@jdxcode Thanks for this note. I'm following up internally. I believe we had a ticket for this already.
